development:
  adapter: postgresql
  encoding: unicode
  database: mental_health_app_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: mental_health_production
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: mental_health_app_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres